### ISSUE TITLE
Adding an option for signature in top at answering

### ISSUE THREAD

**Issue by Siggi0904** [4ch1m/mozext#10]
Hi,

would be great to have an option that the signature will be added in top of an answered mail.

If we answer a big mail, the signature is far at the end. So it's better in top.

Great thanks for this best addon.

**Comment by 4ch1m** [comment]
Hi there,

thanks for your input... but I have disagree on this one.
Let me explain why...

Firstly... IMHO a signature should *always* be located at the very bottom. That's why it's called a *signature*; not an "*include*".

Secondly... if you *answer* to someone's email, then you can assume that he already does have your contact information. So why pollute/clutter the email with redundant/useless information?

Thirdly... a signature usually has a signature-separator ("-- \n"). Or at least it should have one. This separator is often used by email-clients to automatically cut off everything below that signature-separator line on replies. Mainly due to the reason explained above. Otherwise you'd have a mail-body full of signatures after a few reply-bounces.

So... sorry... but no. :smiley:

**Comment by jabrugger** [comment]
A different question could be: My signature, should be at the end of my reply, or at the end of the message (including quotes)?

**Comment by Colonel-Badger** [comment]
Hi Achim,

I'm sorry but I have to agree with Siggi. We have 3 separate companies all using one GSuite email account per user  as well as shared inboxes for support, sales and purchasing addresses with aliases setup for our .co, .co.uk and .com domains. 

A customer may email us into one of our sales@ addresses and then to provide a more personal service, to take ownership of the email and to prevent replies interrupting everyone who monitors the shared inbox, a member of the admin team will reply with their own email, so their signature will be required. 

When they initially email sales, they won't know anyone at our company so a signature is required.  There are then times when our admin team need help (e.g to answer a question for the customer that they don't know the answer to) so will have to copy another member of staff into the email (to the support email perhaps). When support reply, they will want to use their signature directly below their reply so as not to force the user to scroll all the way to the bottom of the email (and many of our customers are visually impaired so it's even more important that people's contact details are accessible directly below are staff's replies in case they need their direct phone number which is different for each member of staff.

The best option I think would be to follow Thunderbird's own rules on this in the Composition and Addressing window:

![image](https://user-images.githubusercontent.com/71727738/96179725-37d95d80-0f29-11eb-80ae-006c85d9bc0f.png)

I really hope you'll reconsider as the signature always appearing right at the bottom when it's turned of and on again has been really annoying for our 10 or so users testing Thunderbird 78!

Please also add in a direct shortcut on the right click menu for signature off (the number 1 reason we use Signature Switch!)

Thanks again for your efforts, it's a brilliant addon.

Kind regards,

Ellis

**Comment by 4ch1m** [comment]
We've had this same exact discussion for about 15 years now... basically since the initial creation of Signature Switch. :smile: 
I totally accept your view on the topic and see the need for this feature based on that use-case.

However, as described above: There are several reasons for me **NOT** to implement it.

Take the following example.
If you make a reply and place your sig above the quote (using the signature separator) then everything below it might be cut off the the receiver's email-client upon his reply.

```
Hi there,
this is my latest reply.
Below is our full discussion.

-- 
Joe Zilla
email: joe@zilla.com
phone: 666

On 10/2/20 8:40 PM, Moe Zilla wrote:
> Hello Joe,
> 
> On 10/2/20 8:34 PM, Joe Zilla wrote:
>>
>> Hi Moe,
>>
>> On 10/2/20 8:33 PM, Moe Zilla wrote:
>>>
>>> Hey Joe,
>>>
>>> this is my initial mail.
>>>
>>> BR,
>>>
>>> Moe
>>>
>> All right. This is the first reply.
>>
>> Cheers,
>>
>> Joe
>>
> So this will be the second reply.
> 
> Regards,
> 
> Moe
> 
```

Having a fixed/defined location of the signature (combined with the signature separator) makes it more easy, efficient, and bullet-proof to detect it.
And this allows features like switching it on/off, cycling through the set, and replacing it with another one possible.

This especially/mainly applies for plaintext-signatures; HTML-signatures do have a different approach (internal tag/attribute).

In general:
I'm open to review a pull-request that handles all use-cases ***and*** corner cases.
But it should not break any of the existing functionality.

Also... I'm totally aware of Thunderird's built-in options regarding this topic ("place my signature below my reply (above the quote)"); which - by the way - when used omits the signature separator (due to the above mentioned reasons); which IMHO is bad.
Besides that: Signature Switch is a pure MailExtension now. And as of now there is no way to read (user-)settings from the global "prefs.js"; at least to my knowledge.

All that being said...
Please also accept my decision.
As an alternative I can recommend using Thunderbird's built-in signature handling or another add-on called "Quicktext" which will insert text-snippets at any desired place within the mail-body.

Thank you!

**Comment by Colonel-Badger** [comment]
I just wanted to say thanks for taking the time to explain this!
