### ISSUE TITLE
Switching rules not working properly

### ISSUE THREAD

**Issue by oparoz** [4ch1m/mozext#13]
I've done some tests with 2 signatures and I can't find a consistent behaviour in how rules are applied.

I think with the previous version the rule was looking at the first address and wouldn't change after that.
In this version, it also changes based on what comes after that, but I can't find the pattern.
I've tried with something like this:
Sig1 is higher than Sig2
`* triggers Sig1, *@domain.com triggers Sig2`

Case 1
U1 U2 U2
-> Sig1
Remove U1
-> Stays as Sig1, which is wrong

Case 2
U2 U1
-> Sig1, even though it's not the 1st one
Add U2
-> No change

Case 3
U2
-> Sig1, which seems to indicate that something is broken.

Case 4
I've changed the order of priority
U2 U1
-> Sig1
Add U2
-> No change, probably because now Sig1 has the highest priority.

I'm guessing priorities play a role, but when I set them right, it doesn't work as expected.
Maybe because I'm using a simple * wildcard for "all emails" as the top priority signature.
I'm trying to set a simple rule where I have one signature for internal messages and another for anything external.

**Comment by 4ch1m** [comment]
Hi,

Firstly... just because it doesn't work like **you expect** it to work, doesn't mean it does not work **properly**. :smile:

Secondly... you can find the code/handling for the auto-switch feature here: [background.js](https://github.com/4ch1m/mozext/blob/master/signatureswitch-me/src/background/background.js)
(`function autoSwitchBasedOnRecipients(tabId = composeActionTabId) ...`)
I'm open for reviewing a pull-request which improves on that.

Thirdly... it makes no sense to use "overlapping patterns" that apply to multiple signatures. You should define unique rules for each signature. E.g. `*@zilla.org,*@acme.com` for signature #1 and `*@my-company.de`.
So, yes... using an "always matching" wildcard like `*` is not how it's intended to work.
