### ISSUE TITLE
Load signature from a file at every start of Thunderbird

### ISSUE THREAD

**Issue by schoettl** [4ch1m/mozext#34]
For our company, an important feature of the old version of SignatureSwitch was that it could load signatures automatically from a file. The signature files were regularly, centrally updated and the employees didn't had to update their signatures themselfes.

Is it planned to add this feature again in this new version?

**Comment by 4ch1m** [comment]
see: [FAQ](http://mozext.achimonline.de/signatureswitch-me.php#faq) (item #6)

I'm currently trying to retrieve "external data" from within SignatureSwitch using native messaging (see dedicated branch).
However, I'm not sure if this will work at all or if I'll invest more time into this.
You're welcome to contribute!

Closing, since this is not an issue.

**Comment by schoettl** [comment]
Thank you.
