### ISSUE TITLE
Auto switch, but by mail account instead of recipients

### ISSUE THREAD

**Issue by Ramel** [4ch1m/mozext#39]
My purpose is to switch the "signature" when I use a different mail account ! Not when I change the recipient. I cannot list all the recipients I send mail to with a specific account!

Hope that can be introduced in a future version.

Thanks.

Ramel

**Comment by 4ch1m** [comment]
> My purpose is to switch the "signature" when I use a different mail account !

Great! Nice for you!

> Not when I change the recipient. I cannot list all the recipients I send mail to with a specific account!

Not quite sure what your problem is!! (<- note the extra exclamation-mark to make my statement more important)

SignatureSwitch allows (automatic) change both based on mail-identity and recipients. Both features are independent from each other.

Closing... since this is not an issue.
