### ISSUE TITLE
Visual separator added by default

### ISSUE THREAD

**Issue by Arcesilas** [4ch1m/mozext#54]
Hi,

I've been using Signature Switch for some time and today, I a long line of dashes appeared to be added just before my signature, except when signature was off.

It took me quite some time to understand what it was : it's the visual separator. Why did it appear now ? No idea... The option as not selected in the configuration. Had to check the box then uncheck it and the visual separator was no more added.

Not a big problem, but it should not appear some day for no reason and when you don't check it (and you don't know it even exists), you may take quite some time to understand what it is.

ANyway thanks for this extension, even if I've lost all my signatures trying to understand what was happening (removed the extension, re-added it, but Thunderbird lost it while running with all my data).

**Comment by 4ch1m** [comment]
Look... I've deliberately made the choice to set the "visual signature separator" as default for everyone. (And I highly recommend to leave this feature activated.)

Neither does this separator get sent with the actual mail-content, nor will it be visible when printing the email, etc.
But hopefully it will mitigate the issues many other users had when accidentally/unawarely composing their message within the signature-paragraph and facing data-loss when switching the signature afterwards (see: #52, #53).

I knew in advance that some users don't like this separator. So I've made this an option.

However, there seems to be a bug, resulting in the default value not correctly being shown when opening the options-ui after a new property gets introduced.
I will try to fix that with the next release. Thanks for bringing this up.

Losing all your settings by uninstalling the add-on is not my fault, but expected behaviour.

In general: If you want to help improve things (better documentation, UX, code, etc.) you're welcome to contribute and/or create a pull-request.

Thanks.
