### ISSUE TITLE
Signature Switch: remove the -- seperator and newline for plain text emails

### ISSUE THREAD

**Issue by notDavid** [4ch1m/mozext#62]
Hi there,

please consider implementing the ability to remove the:
1. `'-- '` prepended before the signature
2. and the newline appended after the signature

(in case of plain text messages.)

Great extension, thank you!

**Comment by 4ch1m** [comment]
Hi @notDavid,

1. The `-- \n` separator is optional for HTML-signatures.
However, it is necessary for plain-text signatures in certain scenarios.
(e.g. actually switching/cycling the signatures in previously saved drafts, etc.)
check: https://github.com/4ch1m/mozext/blob/239ad9a8d9d7497bb432fbee3dbe254842ce0fc0/signatureswitch-me/src/compose/compose.js#L40-L45
Omitting the separator would break functionality.

1. Thunderbird itself also always adds a new line at the very end of every plaintext signature; so I'd like to lean on the standard behaviour here.

Thanks for your feedback.

**Comment by notDavid** [comment]
Hi @4ch1m,

thank you for the detailed description, i understand your reasoning... :-)

**Comment by ErikKrause** [comment]
I like to add information (like opening hours etc.) before the separator, since the signature after the separator is omitted in certain mail clients. I understand the above reasoning, however, would it be possible to remove the separator on sending the message, if another separator is present further down?

**Comment by 4ch1m** [comment]
> I like to add information (like opening hours etc.) before the separator, since the signature after the separator is omitted in certain mail clients.

Then a _signature_ may not be the right way for you to communicate "opening hours".

> I understand the above reasoning, however, would it be possible to remove the separator on sending the message, if another separator is present further down?

No. Sorry.

The sole purpose of this add-on/extension is handling _signatures_.
If your "opening hours" are part of your signature... then they should be placed **below** the signature separator.

If the "opening hours" are **not** part of your signature then this add-on/extension is not the right place to handle your use-case.

Note:
If you need to have signatures with "dynamic content"; you should consider checking out the "[native messaging feature](https://github.com/4ch1m/mozext/tree/master/signatureswitch-me/native_messaging)".

**Comment by ErikKrause** [comment]
You are absolutely right.  However, since signature display can be switched off in certain mail clients and since Signature Switch is all about convenience, it would be nice to have the ability not only to switch between signatures, but also between all kinds of footer texts. The old version worked nice in this regard, and the occasional misfunction after using a draft was negligible.
I will certainly look into native messaging feature, but installing node.js or python for such a tiny task seems a bit overkill.
